# Univariate time series forecasting

In [22]:
# import libraries 
import pandas as pd
import plotly.express as px
import pycaret
from pycaret.time_series import *
from pandas.io.formats import style

In [17]:
# import multivariate data
data = pd.read_csv('data/proc_data/weatherwcity.csv')
data['Date'] = pd.to_datetime(data['Date.Full'])
data = data[['Date','Precipitation']]

In [19]:
# get only date and 
data

           Date  Precipitation
0    2016-01-03           0.00
1    2016-01-10           0.52
2    2016-01-17           0.34
3    2016-01-24           1.55
4    2016-01-31           0.87
...         ...            ...
9323 2016-12-04           0.01
9324 2016-12-11           0.12
9325 2016-12-18           0.26
9326 2016-12-25           0.04
9327 2017-01-01           0.00

[9328 rows x 2 columns]

In [20]:

s = setup(data, target = 'Precipitation',session_id = 123)

In [23]:
best = compare_models(sort = 'MAE')

Initiated  . . . . . . . . . . . . . . . . . .              16:12:25
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

ValueError: Function <function _SupervisedExperiment._highlight_models.<locals>.highlight_max at 0x0000026AA08A7790> resulted in the apply method collapsing to a Series.
Usually, this is the result of the function returning a single value, instead of list-like.